import type { Metadata } from "next";
import { ClarityCity } from "@/utils/customFont";
import "../../app/globals.css";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ClarityCity.variable} `}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
